name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Make build script executable
      - name: Make build script executable
        run: chmod +x ./scripts/build-frontend-if-needed.sh

      # Run yarn build command
      - name: Run yarn build:frontend:if-needed
        run: ./scripts/build-frontend-if-needed.sh

      # Build with Gradle
      - name: Build with Gradle
        run: gradle build

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/**

      # Run Unit Test
      - name: Run Unit Test
        run: gradle test

      # Upload Test Reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/**

      # Generate Code Coverage Report
      - name: Generate code coverage report
        run: gradle jacocoTestReport

      # Upload Code Coverage Report
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/**

      # Run Deployment
      - name: Run Deployment
        run: java -jar build/libs/unleash_test-V1.jar
